steps:

# Decrypt BddTest testsettings.json
#- name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - kms
#  - decrypt
#  - '--ciphertext-file=./$safeprojectname$/testsettings.json.enc'
#  - '--plaintext-file=./$safeprojectname$/testsettings.json'
#  - '--location=europe-west1'
#  - '--keyring=CLOUDBUILD-SECRETS'
#  - '--key=CLOUDBUILD-KEY'
#  id: 'DecryptBddTestsettings'
#  waitFor: ['-']

# Setting browser type variable
- name: 'gcr.io/${PROJECT_ID}/envsubst'
  args: ['./docker.local.env']
  env:
  - '_BROWSER_TYPE=${_BROWSER_TYPE}'
  id: 'BrowserType'
  waitFor: ['-']

# Run integration tests
- id: bdd-test
  name: 'docker/compose:latest'
  args: ['-f', 'docker-compose.yaml', 'up', '--build', '--exit-code-from', 'bdd-test']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
  waitFor: ['BrowserType']

#Timeout
timeout: 1800s
